@startuml

title Backend

database "MySQL (JawsDB)" as mysql

database "Memcached (MemCashier)" as cache

node Node {
   rectangle "Prepared SQL statements" as orm
   rectangle "CRUD interface" as crud
   rectangle "Router" as router
}

cloud "Web (Heroku)" as web

web --> router
router --> crud
router --> cache
crud --> orm
orm --> mysql

@enduml